(define (problem powerdrive-verbatim-2019) (:domain powerdrive-verbatim)
(:objects 
    cgt nex mlx ccoexts ccx hou okc cgttlm mld neb okctlm cco okx cgtpcst ccoextr - location
    pdemba03459 pdemgaexp082 pdemba03460 pdemba03735 pdemba03755 pdemba03423 pdemba03849 pdemba03850 pdemba03838 pdemgaexp125 pdemgaexp080 pdemba03476 pdemba03730 pdemba03851 pdemba03366 pdemga00216 pdemga00231 pdemba500 pdemba03840 pdemba03315 pdemba03823 pdemba03475 pdemba03736 pdemba03158 pdemba03831 pdembaenp04a pdemba03432 pdemgaexp050 pdemba03259hh pdemba03084 pdemba03872 pdemba03011 pdemba03859 pdemba03398 pdemba03679 pdemba03810 pdemba03832 pdemba1123 pdemba02289 pdemba03577 pdemgaexp079 pdemgaexp011 pdemba03794 pdemba03530 pdemba02356 pdemba03771hh pdemgaexp043 pdemba03668 pdembaphx03769 pdemba03672 pdemba03685 pdemba03690 pdemba03949 pdemba03673 pdemba03671 pdembaalt03882 pdemba03655 pdemba03824 pdemba03762 pdemba03483 pdemba03630 pdemgaexp007 pdemba03878 pdemba02260 pdemba03334 pdemba03901 pdemba03615 pdemba03409 pdemgaexp067 pdemba03330 pdemba03256 pdemba1084 pdemba03652 pdemba03532 pdemba03607 pdemba03624 pdemba03738 pdemba03681 pdembaphx03847 pdemba02032 pdembaenp10ht pdemba03448 pdemba03765 pdemba03411 pdemba762 pdemba1165 pdemba03881 pdembaenp06a pdemba03732 pdemba02340 pdemba03038 pdemba03670 pdemba03767 pdemba1008hh pdemba03308 pdemba03436 pdemba03359 pdemba03760 pdemba03718 pdemba03320 pdemba03861 pdemba1254 pdemgaexp036 pdemba03647 pdemgaexp048 pdembaalt03773 pdemba03874 pdemba03412 pdemba02062 pdemba03754 pdemba03756 pdemba03504 pdemba03839 pdemba03643 pdemga00232 pdemba02111 pdemba877 pdemba02308 pdemgaexp025 pdemba803 pdemba669 pdemba1087 pdemba03863 pdemba03221 pdemba03834 pdemba03723 pdemba03107 pdemba03662 pdemba03807 pdemba03517 pdemba03153ht pdemba03821 pdemba095 pdemba03496ht pdemba03804 pdemba03520 pdemba03676 pdemba03190 pdemba03748 pdemba03482 pdemba03835 pdemgaexp077 pdemba03737 pdemba03945 pdemba03474 pdemba03191 pdemgaexp087 pdemba03880 pdembaenp31aht pdemba1144 pdemba03494 pdemba03842 pdemgaexp056 pdemba03049hh pdemba03333 pdemba03653 pdemba03853 pdemba03899 pdemgaexp038 pdemba1216 pdemba03033 pdemba03761 pdemgaexp085 pdemba03276 pdemgaexp086 pdemba03488ht pdemba03725 pdemba03820 pdemgaexp073 pdemba03427 pdemba03708 pdemba038 pdemba03802 pdemba03324 pdemba03876 pdemba03518 pdembaalt03793 pdemba03857 pdemba03739 pdemgaexp076 pdemba03147 pdemba02108 pdemba03941 pdemba03392 pdemba1098 pdemba03160 pdemba03763 pdemba02017ht pdemba03704 pdemba03623 pdemba03451 pdemba1040 pdemba03827 pdemba03527 pdemba03639 pdemba03201 pdemba03440 pdemba03523 pdemba02036 pdemba03809 pdemba695 pdemgaexp072 pdemba02028 pdemba03659 pdemba03480 pdemba02177 pdemba03808 pdemgaexp061 pdemba03825 pdemba03696 pdemba03454 pdemba03943 pdemba03612 pdemba03871 pdemba03716 pdemba03592 pdemba744 pdemba03890 pdemgaexp078 pdembaphx03798 pdemba03194 pdembaenp04 pdemba03726 pdemgaexp075 pdemba03948 pdemgaexp010 pdemba03664 pdemba03489 pdemba03645 pdemba03677 pdemba1204 pdemgaexp103 pdemgaexp019 pdemba03421 pdemba03946 pdemba03770 pdemba02303 pdemgaexp111 pdemga00237 pdemgaexp068 pdemba03453 pdembaenp13ahh pdemba03826 pdembaenp07a pdemba1166 pdemba03013 pdemba1220 pdemgaexp060 pdemba03843 pdemgaexp084 pdemba03879 pdemba03629 pdemba03805 pdemba03230 pdembaalt03875 pdemgaexp083 pdemba03883 pdembaphx03830 pdemba03743 pdemba03372 pdemba03397 pdemba03803 pdemba03144 pdemba02022ht pdembaphx03796 pdemba03800 pdembaphx03845 pdemba356 pdemba02190 pdemba03822 pdemba03649 pdemba03642 pdembaenp43 pdemga00217 pdemba02114 pdemba02038 pdemba03722 pdemba03661 pdemba02286hh pdemgaexp055 pdemba03512 pdemba03665 pdemba03806 pdemgaexp081 pdemba03402 pdemba03479 pdemba03684 pdemba03640 pdembaenp01 pdemba03942 pdemba03146 pdemgaexp062 pdembaenp59 pdemgaexp070 pdemba03904 pdemba03507 pdemba03430 pdemba03854 pdemba03252 pdemba03742 pdemba03375 pdemba03076ht pdemga00230 pdemba03720 pdemba03582 pdemgaexp113 pdemba03939 pdemba03446 pdemba00489 pdemgaexp112 pdemgaexp069 pdemba03017 pdemba03703 pdemba03529ht pdemba03744 pdemba03795 pdemba03336 pdemba03187 pdemba1235 pdemba02269 pdemba672hh pdemba03759 pdemgaexp094 pdemba03367 pdemba02262 pdemba03245 pdemba03660 pdemba03869 pdemba03688 pdemba748 pdemba03841 pdemba03766 pdemgaexp074 pdemba03503 - tool
)

(:init
	(at pdemba00489 neb)
	(at pdemba02017ht cgttlm)
	(at pdemba02022ht cgttlm)
	(at pdemba02028 mlx)
	(at pdemba02032 mlx)
	(at pdemba02036 mld)
	(at pdemba02038 cgtpcst)
	(at pdemba02062 ccoextr)
	(at pdemba02108 cgtpcst)
	(at pdemba02111 mld)
	(at pdemba02114 mld)
	(at pdemba02177 ccoextr)
	(at pdemba02190 mlx)
	(at pdemba02260 mlx)
	(at pdemba02269 cgtpcst)
	(at pdemba02286hh cco)
	(at pdemba02289 ccoextr)
	(at pdemba02303 cgtpcst)
	(at pdemba02308 mlx)
	(at pdemba02340 okctlm)
	(at pdemba02356 ccoextr)
	(at pdemba03011 ccoextr)
	(at pdemba03013 okx)
	(at pdemba03017 ccoextr)
	(at pdemba03033 ccoextr)
	(at pdemba03038 okctlm)
	(at pdemba03049hh okctlm)
	(at pdemba03076ht cgttlm)
	(at pdemba03084 mld)
	(at pdemba03107 cgtpcst)
	(at pdemba03144 cgttlm)
	(at pdemba03146 mlx)
	(at pdemba03147 mlx)
	(at pdemba03153ht cgttlm)
	(at pdemba03158 mld)
	(at pdemba03160 cgttlm)
	(at pdemba03187 cgttlm)
	(at pdemba03190 cgtpcst)
	(at pdemba03191 neb)
	(at pdemba03194 mlx)
	(at pdemba03201 nex)
	(at pdemba03221 ccoextr)
	(at pdemba03230 okx)
	(at pdemba03245 okctlm)
	(at pdemba03252 okctlm)
	(at pdemba03256 cgtpcst)
	(at pdemba03259hh okctlm)
	(at pdemba03276 ccoextr)
	(at pdemba03308 neb)
	(at pdemba03315 ccoextr)
	(at pdemba03320 okctlm)
	(at pdemba03324 cgtpcst)
	(at pdemba03330 cgtpcst)
	(at pdemba03333 cco)
	(at pdemba03334 mlx)
	(at pdemba03336 okctlm)
	(at pdemba03359 cgtpcst)
	(at pdemba03366 okctlm)
	(at pdemba03367 okctlm)
	(at pdemba03372 mld)
	(at pdemba03375 okx)
	(at pdemba03392 mld)
	(at pdemba03397 cco)
	(at pdemba03398 cgttlm)
	(at pdemba03402 neb)
	(at pdemba03409 ccoextr)
	(at pdemba03411 nex)
	(at pdemba03412 ccoextr)
	(at pdemba03421 cgtpcst)
	(at pdemba03423 mld)
	(at pdemba03427 ccoextr)
	(at pdemba03430 mld)
	(at pdemba03432 okctlm)
	(at pdemba03436 ccoextr)
	(at pdemba03440 okc)
	(at pdemba03446 ccoextr)
	(at pdemba03448 okctlm)
	(at pdemba03451 mld)
	(at pdemba03453 mld)
	(at pdemba03454 neb)
	(at pdemba03459 cco)
	(at pdemba03460 cco)
	(at pdemba03474 cgtpcst)
	(at pdemba03476 mlx)
	(at pdemba03479 mld)
	(at pdemba03480 mld)
	(at pdemba03482 mld)
	(at pdemba03483 cgtpcst)
	(at pdemba03488ht cgttlm)
	(at pdemba03489 okctlm)
	(at pdemba03494 cgtpcst)
	(at pdemba03496ht cgttlm)
	(at pdemba03503 mlx)
	(at pdemba03504 cgtpcst)
	(at pdemba03507 okctlm)
	(at pdemba03512 okc)
	(at pdemba03517 okctlm)
	(at pdemba03518 cgtpcst)
	(at pdemba03520 ccoextr)
	(at pdemba03523 cgtpcst)
	(at pdemba03527 ccoextr)
	(at pdemba03529ht cgttlm)
	(at pdemba03530 okctlm)
	(at pdemba03532 cgtpcst)
	(at pdemba03577 neb)
	(at pdemba03582 mlx)
	(at pdemba03592 mld)
	(at pdemba03607 ccoextr)
	(at pdemba03612 ccoextr)
	(at pdemba03615 ccoextr)
	(at pdemba03623 mlx)
	(at pdemba03624 okctlm)
	(at pdemba03629 ccoextr)
	(at pdemba03630 okc)
	(at pdemba03639 cgtpcst)
	(at pdemba03640 okx)
	(at pdemba03642 hou)
	(at pdemba03643 mlx)
	(at pdemba03645 neb)
	(at pdemba03647 ccoextr)
	(at pdemba03649 hou)
	(at pdemba03652 mlx)
	(at pdemba03653 ccoextr)
	(at pdemba03655 mlx)
	(at pdemba03659 mlx)
	(at pdemba03660 cgtpcst)
	(at pdemba03661 ccoextr)
	(at pdemba03662 cgtpcst)
	(at pdemba03664 cgtpcst)
	(at pdemba03665 mlx)
	(at pdemba03668 cgtpcst)
	(at pdemba03670 mlx)
	(at pdemba03671 mld)
	(at pdemba03672 mlx)
	(at pdemba03673 okx)
	(at pdemba03676 okctlm)
	(at pdemba03677 mlx)
	(at pdemba03679 ccoextr)
	(at pdemba03681 mlx)
	(at pdemba03684 mlx)
	(at pdemba03685 ccoextr)
	(at pdemba03688 mlx)
	(at pdemba03690 okc)
	(at pdemba03696 cco)
	(at pdemba03703 ccoextr)
	(at pdemba03704 mlx)
	(at pdemba03708 ccoextr)
	(at pdemba03716 mlx)
	(at pdemba03718 ccoextr)
	(at pdemba03720 cco)
	(at pdemba03722 mld)
	(at pdemba03723 ccoextr)
	(at pdemba03725 okc)
	(at pdemba03726 neb)
	(at pdemba03730 okctlm)
	(at pdemba03732 mld)
	(at pdemba03735 mld)
	(at pdemba03736 mld)
	(at pdemba03737 mld)
	(at pdemba03738 mlx)
	(at pdemba03739 mld)
	(at pdemba03742 mlx)
	(at pdemba03743 okx)
	(at pdemba03744 okx)
	(at pdemba03748 mlx)
	(at pdemba03754 mld)
	(at pdemba03755 mld)
	(at pdemba03756 mld)
	(at pdemba03759 mlx)
	(at pdemba03760 okc)
	(at pdemba03761 mld)
	(at pdemba03762 nex)
	(at pdemba03763 okctlm)
	(at pdemba03765 okctlm)
	(at pdemba03766 okx)
	(at pdemba03767 mlx)
	(at pdemba03770 mlx)
	(at pdemba03771hh cgttlm)
	(at pdemba03794 okctlm)
	(at pdemba03795 okctlm)
	(at pdemba038 cgtpcst)
	(at pdemba03800 mlx)
	(at pdemba03802 okctlm)
	(at pdemba03803 ccoexts)
	(at pdemba03804 okx)
	(at pdemba03805 okctlm)
	(at pdemba03806 mld)
	(at pdemba03807 mld)
	(at pdemba03808 okx)
	(at pdemba03809 ccoexts)
	(at pdemba03810 neb)
	(at pdemba03820 mld)
	(at pdemba03821 cco)
	(at pdemba03822 hou)
	(at pdemba03823 mld)
	(at pdemba03824 okctlm)
	(at pdemba03825 neb)
	(at pdemba03826 cco)
	(at pdemba03827 neb)
	(at pdemba03831 okc)
	(at pdemba03832 okctlm)
	(at pdemba03834 mld)
	(at pdemba03835 okctlm)
	(at pdemba03838 cco)
	(at pdemba03839 mld)
	(at pdemba03840 ccoexts)
	(at pdemba03841 cco)
	(at pdemba03842 mlx)
	(at pdemba03843 okctlm)
	(at pdemba03849 ccoextr)
	(at pdemba03850 ccoextr)
	(at pdemba03851 ccoextr)
	(at pdemba03853 okx)
	(at pdemba03854 mld)
	(at pdemba03857 mld)
	(at pdemba03859 ccoexts)
	(at pdemba03861 ccoextr)
	(at pdemba03863 ccoextr)
	(at pdemba03869 mld)
	(at pdemba03871 cgtpcst)
	(at pdemba03872 cgtpcst)
	(at pdemba03876 cgtpcst)
	(at pdemba03878 cgtpcst)
	(at pdemba03879 cgtpcst)
	(at pdemba03880 mld)
	(at pdemba03883 mlx)
	(at pdemba03901 ccoexts)
	(at pdemba03904 ccoexts)
	(at pdemba095 mld)
	(at pdemba1008hh okctlm)
	(at pdemba1040 cgtpcst)
	(at pdemba1084 okctlm)
	(at pdemba1087 cgtpcst)
	(at pdemba1098 cgtpcst)
	(at pdemba1123 okctlm)
	(at pdemba1144 mlx)
	(at pdemba1165 cgtpcst)
	(at pdemba1166 ccoextr)
	(at pdemba1204 mld)
	(at pdemba1216 ccoextr)
	(at pdemba1220 cgtpcst)
	(at pdemba1235 cgtpcst)
	(at pdemba1254 mlx)
	(at pdemba356 ccoextr)
	(at pdemba500 okc)
	(at pdemba669 ccoextr)
	(at pdemba672hh cgttlm)
	(at pdemba695 neb)
	(at pdemba744 cgtpcst)
	(at pdemba748 okctlm)
	(at pdemba762 mlx)
	(at pdemba803 okctlm)
	(at pdemba877 mlx)
	(at pdembaalt03773 mlx)
	(at pdembaalt03793 ccoexts)
	(at pdembaalt03875 ccoexts)
	(at pdembaalt03882 mlx)
	(at pdembaenp01 cgtpcst)
	(at pdembaenp04 mld)
	(at pdembaenp04a cgtpcst)
	(at pdembaenp06a cgttlm)
	(at pdembaenp07a mld)
	(at pdembaenp10ht cgttlm)
	(at pdembaenp13ahh okctlm)
	(at pdembaenp31aht cgttlm)
	(at pdembaenp43 mlx)
	(at pdembaenp59 okctlm)
	(at pdembaphx03769 mlx)
	(at pdembaphx03796 mlx)
	(at pdembaphx03798 mlx)
	(at pdembaphx03830 mlx)
	(at pdembaphx03845 mlx)
	(at pdembaphx03847 mlx)
	(at pdemgaexp007 mld)
	(at pdemgaexp010 neb)
	(at pdemgaexp011 okctlm)
	(at pdemgaexp019 okctlm)
	(at pdemgaexp025 cco)
	(at pdemgaexp036 okx)
	(at pdemgaexp038 mld)
	(at pdemgaexp043 cco)
	(at pdemgaexp048 mlx)
	(at pdemgaexp050 mld)
	(at pdemgaexp055 okc)
	(at pdemgaexp056 ccoextr)
	(at pdemgaexp060 cgttlm)
	(at pdemgaexp061 cgttlm)
	(at pdemgaexp062 okctlm)
	(at pdemgaexp067 okctlm)
	(at pdemgaexp068 mld)
	(at pdemgaexp069 okctlm)
	(at pdemgaexp070 mld)
	(at pdemgaexp072 mld)
	(at pdemgaexp073 okctlm)
	(at pdemgaexp074 cco)
	(at pdemgaexp075 neb)
	(at pdemgaexp076 mld)
	(at pdemgaexp077 mlx)
	(at pdemgaexp078 neb)
	(at pdemgaexp079 hou)
	(at pdemgaexp080 mld)
	(at pdemgaexp081 mld)
	(at pdemgaexp082 mld)
	(at pdemgaexp083 neb)
	(at pdemgaexp084 mld)
	(at pdemgaexp085 mld)
	(at pdemgaexp086 okctlm)
	(at pdemgaexp087 okctlm)
	(at pdemba03874 ccoexts)
	(at pdemba03881 ccoexts)
	(at pdemba03890 ccoexts)
	(at pdemba03899 ccoexts)
	(at pdemba03939 ccoexts)
	(at pdemba03942 ccoexts)
	(at pdemba03943 ccoexts)
	(at pdemba03945 ccoexts)
	(at pdemba03946 ccoexts)
	(at pdemba03948 ccoexts)
	(at pdemba03949 ccoexts)
	(at pdemba03941 ccoexts)
	(at pdemgaexp094 ccoexts)
	(at pdemgaexp103 ccoexts)
	(at pdemgaexp111 ccoexts)
	(at pdemgaexp112 ccoextr)
	(at pdemgaexp113 ccoextr)
	(at pdemgaexp125 ccoexts)
	(at pdemga00216 okctlm)
	(at pdemga00217 okctlm)
	(at pdemba02262 ccoextr)
	(at pdemba03475 ccoextr)
	(at pdemga00231 okctlm)
	(at pdemga00232 okctlm)
	(at pdemga00230 okctlm)
	(at pdemga00237 okctlm)
	(= (number-of-tools-at cgt) 0)
	(= (number-of-tools-at nex) 3)
	(= (number-of-tools-at mlx) 50)
	(= (number-of-tools-at ccoexts) 24)
	(= (number-of-tools-at ccx) 0)
	(= (number-of-tools-at hou) 4)
	(= (number-of-tools-at okc) 9)
	(= (number-of-tools-at cgttlm) 18)
	(= (number-of-tools-at mld) 52)
	(= (number-of-tools-at neb) 16)
	(= (number-of-tools-at okctlm) 50)
	(= (number-of-tools-at cco) 14)
	(= (number-of-tools-at okx) 12)
	(= (number-of-tools-at cgtpcst) 38)
	(= (number-of-tools-at ccoextr) 44)
	(= (number-of-tools-in-state fxd-pendingassemblystate) 0)
	(= (number-of-tools-in-state transferred-permanentstate) 0)
	(= (number-of-tools-in-state rong-failedunderanalysisstate) 0)
	(= (number-of-tools-in-state onlocation-transittobasestate) 0)
	(= (number-of-tools-in-state onlocation-onlocationstate) 0)
	(= (number-of-tools-in-state rong-underservicestate) 0)
	(= (number-of-tools-in-state rong-failedstate) 0)
	(= (number-of-tools-in-state fxd-assembledstate) 0)
	(= (number-of-tools-in-state in-transitstate) 0)
	(= (number-of-tools-in-state fxd-wopendingstate) 0)
	(= (number-of-tools-in-state rite-rffstate) 0)
	(= (number-of-tools-in-state rong-usedstate) 0)
	(= (number-of-tools-in-state fxd-underservicestate) 0)
	(= (number-of-tools-in-state onlocation-transittorigstate) 0)
	(= (number-of-tools-in-state rite-inprocessstate) 0)
	(= (number-of-tools-in-state transferred-repairstate) 0)
	(= (number-of-tools-in-state rong-repairstate) 0)
	(= (number-of-tools-in-state fxd-pendingapprovalstate) 0)
	(= (number-of-tools-in-state transferred-loanedstate) 0)
	;;(= (number-of-tools-in-state-fxd-pendingassembly) 0)
	;;(= (number-of-tools-in-state-transferred-permanent) 0)
	;;(= (number-of-tools-in-state-rong-failedunderanalysis) 0)
	;;(= (number-of-tools-in-state-onlocation-transittobase) 0)
	;;(= (number-of-tools-in-state-onlocation-onlocation) 0)
	;;(= (number-of-tools-in-state-rong-underservice) 0)
	;;(= (number-of-tools-in-state-rong-failed) 0)
	;;(= (number-of-tools-in-state-fxd-assembled) 0)
	;;(= (number-of-tools-in-state-in-transit) 0)
	;;(= (number-of-tools-in-state-fxd-wopending) 0)
	;;(= (number-of-tools-in-state-rite-rff) 0)
	;;(= (number-of-tools-in-state-rong-used) 0)
	;;(= (number-of-tools-in-state-fxd-underservice) 0)
	;;(= (number-of-tools-in-state-onlocation-transittorig) 0)
	;;(= (number-of-tools-in-state-rite-inprocess) 0)
	;;(= (number-of-tools-in-state-transferred-repair) 0)
	;;(= (number-of-tools-in-state-rong-repair) 0)
	;;(= (number-of-tools-in-state-fxd-pendingapproval) 0)
	;;(= (number-of-tools-in-state-transferred-loaned) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate cgt) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate nex) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate mlx) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate ccoexts) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate ccx) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate hou) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate okc) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate cgttlm) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate mld) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate neb) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate okctlm) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate cco) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate okx) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate cgtpcst) 0)
	(= (number-of-tools-in-state-location fxd-pendingassemblystate ccoextr) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate cgt) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate nex) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate mlx) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate ccoexts) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate ccx) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate hou) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate okc) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate cgttlm) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate mld) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate neb) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate okctlm) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate cco) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate okx) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate cgtpcst) 0)
	(= (number-of-tools-in-state-location transferred-permanentstate ccoextr) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate cgt) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate nex) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate mlx) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate ccoexts) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate ccx) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate hou) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate okc) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate cgttlm) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate mld) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate neb) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate okctlm) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate cco) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate okx) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate cgtpcst) 0)
	(= (number-of-tools-in-state-location rong-failedunderanalysisstate ccoextr) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate cgt) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate nex) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate mlx) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate ccoexts) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate ccx) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate hou) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate okc) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate cgttlm) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate mld) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate neb) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate okctlm) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate cco) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate okx) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate cgtpcst) 0)
	(= (number-of-tools-in-state-location onlocation-transittobasestate ccoextr) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate cgt) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate nex) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate mlx) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate ccoexts) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate ccx) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate hou) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate okc) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate cgttlm) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate mld) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate neb) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate okctlm) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate cco) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate okx) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate cgtpcst) 0)
	(= (number-of-tools-in-state-location onlocation-onlocationstate ccoextr) 0)
	(= (number-of-tools-in-state-location rong-underservicestate cgt) 0)
	(= (number-of-tools-in-state-location rong-underservicestate nex) 0)
	(= (number-of-tools-in-state-location rong-underservicestate mlx) 0)
	(= (number-of-tools-in-state-location rong-underservicestate ccoexts) 0)
	(= (number-of-tools-in-state-location rong-underservicestate ccx) 0)
	(= (number-of-tools-in-state-location rong-underservicestate hou) 0)
	(= (number-of-tools-in-state-location rong-underservicestate okc) 0)
	(= (number-of-tools-in-state-location rong-underservicestate cgttlm) 0)
	(= (number-of-tools-in-state-location rong-underservicestate mld) 0)
	(= (number-of-tools-in-state-location rong-underservicestate neb) 0)
	(= (number-of-tools-in-state-location rong-underservicestate okctlm) 0)
	(= (number-of-tools-in-state-location rong-underservicestate cco) 0)
	(= (number-of-tools-in-state-location rong-underservicestate okx) 0)
	(= (number-of-tools-in-state-location rong-underservicestate cgtpcst) 0)
	(= (number-of-tools-in-state-location rong-underservicestate ccoextr) 0)
	(= (number-of-tools-in-state-location rong-failedstate cgt) 0)
	(= (number-of-tools-in-state-location rong-failedstate nex) 0)
	(= (number-of-tools-in-state-location rong-failedstate mlx) 0)
	(= (number-of-tools-in-state-location rong-failedstate ccoexts) 0)
	(= (number-of-tools-in-state-location rong-failedstate ccx) 0)
	(= (number-of-tools-in-state-location rong-failedstate hou) 0)
	(= (number-of-tools-in-state-location rong-failedstate okc) 0)
	(= (number-of-tools-in-state-location rong-failedstate cgttlm) 0)
	(= (number-of-tools-in-state-location rong-failedstate mld) 0)
	(= (number-of-tools-in-state-location rong-failedstate neb) 0)
	(= (number-of-tools-in-state-location rong-failedstate okctlm) 0)
	(= (number-of-tools-in-state-location rong-failedstate cco) 0)
	(= (number-of-tools-in-state-location rong-failedstate okx) 0)
	(= (number-of-tools-in-state-location rong-failedstate cgtpcst) 0)
	(= (number-of-tools-in-state-location rong-failedstate ccoextr) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate cgt) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate nex) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate mlx) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate ccoexts) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate ccx) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate hou) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate okc) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate cgttlm) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate mld) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate neb) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate okctlm) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate cco) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate okx) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate cgtpcst) 0)
	(= (number-of-tools-in-state-location fxd-assembledstate ccoextr) 0)
	(= (number-of-tools-in-state-location in-transitstate cgt) 0)
	(= (number-of-tools-in-state-location in-transitstate nex) 0)
	(= (number-of-tools-in-state-location in-transitstate mlx) 0)
	(= (number-of-tools-in-state-location in-transitstate ccoexts) 0)
	(= (number-of-tools-in-state-location in-transitstate ccx) 0)
	(= (number-of-tools-in-state-location in-transitstate hou) 0)
	(= (number-of-tools-in-state-location in-transitstate okc) 0)
	(= (number-of-tools-in-state-location in-transitstate cgttlm) 0)
	(= (number-of-tools-in-state-location in-transitstate mld) 0)
	(= (number-of-tools-in-state-location in-transitstate neb) 0)
	(= (number-of-tools-in-state-location in-transitstate okctlm) 0)
	(= (number-of-tools-in-state-location in-transitstate cco) 0)
	(= (number-of-tools-in-state-location in-transitstate okx) 0)
	(= (number-of-tools-in-state-location in-transitstate cgtpcst) 0)
	(= (number-of-tools-in-state-location in-transitstate ccoextr) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate cgt) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate nex) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate mlx) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate ccoexts) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate ccx) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate hou) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate okc) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate cgttlm) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate mld) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate neb) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate okctlm) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate cco) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate okx) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate cgtpcst) 0)
	(= (number-of-tools-in-state-location fxd-wopendingstate ccoextr) 0)
	(= (number-of-tools-in-state-location rite-rffstate cgt) 0)
	(= (number-of-tools-in-state-location rite-rffstate nex) 0)
	(= (number-of-tools-in-state-location rite-rffstate mlx) 0)
	(= (number-of-tools-in-state-location rite-rffstate ccoexts) 0)
	(= (number-of-tools-in-state-location rite-rffstate ccx) 0)
	(= (number-of-tools-in-state-location rite-rffstate hou) 0)
	(= (number-of-tools-in-state-location rite-rffstate okc) 0)
	(= (number-of-tools-in-state-location rite-rffstate cgttlm) 0)
	(= (number-of-tools-in-state-location rite-rffstate mld) 0)
	(= (number-of-tools-in-state-location rite-rffstate neb) 0)
	(= (number-of-tools-in-state-location rite-rffstate okctlm) 0)
	(= (number-of-tools-in-state-location rite-rffstate cco) 0)
	(= (number-of-tools-in-state-location rite-rffstate okx) 0)
	(= (number-of-tools-in-state-location rite-rffstate cgtpcst) 0)
	(= (number-of-tools-in-state-location rite-rffstate ccoextr) 0)
	(= (number-of-tools-in-state-location rong-usedstate cgt) 0)
	(= (number-of-tools-in-state-location rong-usedstate nex) 0)
	(= (number-of-tools-in-state-location rong-usedstate mlx) 0)
	(= (number-of-tools-in-state-location rong-usedstate ccoexts) 0)
	(= (number-of-tools-in-state-location rong-usedstate ccx) 0)
	(= (number-of-tools-in-state-location rong-usedstate hou) 0)
	(= (number-of-tools-in-state-location rong-usedstate okc) 0)
	(= (number-of-tools-in-state-location rong-usedstate cgttlm) 0)
	(= (number-of-tools-in-state-location rong-usedstate mld) 0)
	(= (number-of-tools-in-state-location rong-usedstate neb) 0)
	(= (number-of-tools-in-state-location rong-usedstate okctlm) 0)
	(= (number-of-tools-in-state-location rong-usedstate cco) 0)
	(= (number-of-tools-in-state-location rong-usedstate okx) 0)
	(= (number-of-tools-in-state-location rong-usedstate cgtpcst) 0)
	(= (number-of-tools-in-state-location rong-usedstate ccoextr) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate cgt) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate nex) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate mlx) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate ccoexts) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate ccx) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate hou) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate okc) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate cgttlm) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate mld) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate neb) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate okctlm) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate cco) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate okx) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate cgtpcst) 0)
	(= (number-of-tools-in-state-location fxd-underservicestate ccoextr) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate cgt) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate nex) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate mlx) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate ccoexts) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate ccx) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate hou) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate okc) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate cgttlm) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate mld) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate neb) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate okctlm) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate cco) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate okx) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate cgtpcst) 0)
	(= (number-of-tools-in-state-location onlocation-transittorigstate ccoextr) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate cgt) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate nex) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate mlx) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate ccoexts) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate ccx) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate hou) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate okc) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate cgttlm) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate mld) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate neb) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate okctlm) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate cco) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate okx) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate cgtpcst) 0)
	(= (number-of-tools-in-state-location rite-inprocessstate ccoextr) 0)
	(= (number-of-tools-in-state-location transferred-repairstate cgt) 0)
	(= (number-of-tools-in-state-location transferred-repairstate nex) 0)
	(= (number-of-tools-in-state-location transferred-repairstate mlx) 0)
	(= (number-of-tools-in-state-location transferred-repairstate ccoexts) 0)
	(= (number-of-tools-in-state-location transferred-repairstate ccx) 0)
	(= (number-of-tools-in-state-location transferred-repairstate hou) 0)
	(= (number-of-tools-in-state-location transferred-repairstate okc) 0)
	(= (number-of-tools-in-state-location transferred-repairstate cgttlm) 0)
	(= (number-of-tools-in-state-location transferred-repairstate mld) 0)
	(= (number-of-tools-in-state-location transferred-repairstate neb) 0)
	(= (number-of-tools-in-state-location transferred-repairstate okctlm) 0)
	(= (number-of-tools-in-state-location transferred-repairstate cco) 0)
	(= (number-of-tools-in-state-location transferred-repairstate okx) 0)
	(= (number-of-tools-in-state-location transferred-repairstate cgtpcst) 0)
	(= (number-of-tools-in-state-location transferred-repairstate ccoextr) 0)
	(= (number-of-tools-in-state-location rong-repairstate cgt) 0)
	(= (number-of-tools-in-state-location rong-repairstate nex) 0)
	(= (number-of-tools-in-state-location rong-repairstate mlx) 0)
	(= (number-of-tools-in-state-location rong-repairstate ccoexts) 0)
	(= (number-of-tools-in-state-location rong-repairstate ccx) 0)
	(= (number-of-tools-in-state-location rong-repairstate hou) 0)
	(= (number-of-tools-in-state-location rong-repairstate okc) 0)
	(= (number-of-tools-in-state-location rong-repairstate cgttlm) 0)
	(= (number-of-tools-in-state-location rong-repairstate mld) 0)
	(= (number-of-tools-in-state-location rong-repairstate neb) 0)
	(= (number-of-tools-in-state-location rong-repairstate okctlm) 0)
	(= (number-of-tools-in-state-location rong-repairstate cco) 0)
	(= (number-of-tools-in-state-location rong-repairstate okx) 0)
	(= (number-of-tools-in-state-location rong-repairstate cgtpcst) 0)
	(= (number-of-tools-in-state-location rong-repairstate ccoextr) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate cgt) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate nex) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate mlx) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate ccoexts) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate ccx) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate hou) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate okc) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate cgttlm) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate mld) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate neb) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate okctlm) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate cco) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate okx) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate cgtpcst) 0)
	(= (number-of-tools-in-state-location fxd-pendingapprovalstate ccoextr) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate cgt) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate nex) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate mlx) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate ccoexts) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate ccx) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate hou) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate okc) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate cgttlm) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate mld) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate neb) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate okctlm) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate cco) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate okx) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate cgtpcst) 0)
	(= (number-of-tools-in-state-location transferred-loanedstate ccoextr) 0)
)
(:goal (and
    (>= (number-of-tools-in-state in-transitstate) 0)
)))